import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import ReactQueryProvider from "@/context/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AuthProvider>
				<body className={inter.className}>
					<ThemeProvider
						attribute="class"
						enableSystem
						disableTransitionOnChange
						defaultTheme="system">
						<ReactQueryProvider>
							<main>{children}</main>
						</ReactQueryProvider>
						<Toaster />
					</ThemeProvider>
				</body>
			</AuthProvider>
		</html>
	);
}
